/**
 * This file is used with PhantomJS to make a static dump of the index page
 * generated by `index.js`.
 *
 * $ phantomjs index.dump.js <template.html> <index.js> <sitemap.json> <output.html>
 */

var page        = require("webpage").create()
  , system      = require("system")
  , fs          = require("fs")
  , template    = system.args[1]
  , indexjs     = system.args[2]
  , sitemap     = system.args[3]
  , destination = system.args[4];

var files = [template, sitemap, indexjs];
for(var i = 0, file; file = files[i++];) if(!fs.isFile(file)){
    console.log(file + " doesn't exist.");
    phantom.exit();
}
if(fs.isDirectory(destination)){
    console.log("Target destination is a directory.");
    phantom.exit();
}


page.open(template, function(){
    page.onCallback = function(data){
        var fn = fs.absolute(destination);
        console.log("Writing "+fn+" ...");
        fs.write(fn, data, "w");
        phantom.exit();
    };
    
    page.evaluate(function(js, data){
        document.title = 'Index';
        var ROOT = "./";
        eval(js);
        process(data);
        follow(INDEX);
        window.callPhantom(
            "<!DOCTYPE html>" + document.documentElement.outerHTML
        );
    }, fs.read(indexjs), fs.read(sitemap));
    phantom.exit();
});
