baseURL: ""
languageCode: "en-gb"
title: "Snel"
metaDataFormat: "yaml"
relativeURLs: true
uglyURLs: true
disableLiveReload: true
enableGitInfo: true
enableRobotsTXT: true
params:
    author: "Anonymous"
disableKinds:
-   taxonomy
-   taxonomyTerm
