#!/bin/bash

# Wrapper that leverages a `make` recipe into compiling a static website.
# The first argument is the source directory (default: current directory),
# second argument is the destination directory (default: `dist` in sourc)

SNEL="$(dirname "$(readlink --canonicalize $0)")"
SRC="${2:-$PWD}"
DEST="${3:-$SRC/build}"
MAKE="make --makefile="$SNEL/makefile""

case $1 in
    build )
        # Execute twice: on the first run, the pages are created; on the
        # second, auxiliary files that were referenced in the files are
        # generated
        for TARGET in html resources; do
            $MAKE \
                SNEL="$SNEL" \
                SRC="$SRC/content" \
                THEME="$SRC/theme" \
                DEST="$DEST" \
                "$TARGET" || exit
        done
         ;;
    upload )
        $MAKE upload-ftp ;;
    * )
        echo \
"\
Usage: 
    snel ACTION [SOURCE] [TARGET]
    
ACTION: build|upload

SOURCE: Directory with a content and theme directory. Default: current directory.

TARGET: Build directory.
";;
esac



