# This adds recipes for generating PDF documents, plus associated styles.

ifeq (,$(filter %/snel.mk snel.mk,$(MAKEFILE_LIST)))
$(error The main snel.mk module was not loaded)
endif

$(DEST)/%.css: $(STYLE_DIR)/%.scss $(wildcard $(STYLE_DIR)/_*.scss)
	@-mkdir -p $(@D)
	sassc --style compressed $< $@

$(DEST)/%.pdf: \
		$(SRC)/%.md \
		$(PANDOC_DIR)/link.lua \
		$(PANDOC_DIR)/page.html # additional deps generated by dynamic.mk in snel-index.mk
	@echo "Generating document \"$@\"..." 1>&2
	@-mkdir -p "$(@D)"
	@pandoc \
		--shift-heading-level-by=1 \
		--pdf-engine=weasyprint \
		--pdf-engine-opt=-u"$(@D)" \
		--template '$(PANDOC_DIR)/page.html' \
		--metadata root='$(shell realpath $(DEST) --relative-to $(@D) --canonicalize-missing)' \
		$(foreach F,$(filter %.lua, $^), --lua-filter='$(F)') \
		--to pdf \
		$< \
	| ps2pdf \
		-dOptimize=true \
		-dUseFlateCompression=true \
		-dEmbedAllFonts=true \
		-dPrinted=false \
		- $@

