# This adds recipes for generating PDF or HTML documents and associated
# resources.

include $(dir $(abspath $(lastword $(MAKEFILE_LIST))))/snel-variables.mk

$(DEST)/%.css: $(STYLE_DIR)/%.scss $(wildcard $(STYLE_DIR)/_*.scss)
	@-mkdir -p $(@D)
	sassc --style compressed $< $@

# Create HTML documents
# The following targets are required once but do not influence the build of this
# target: $(DEST)/$(STYLE).css $(DEST)/favicon.ico
$(DEST)/%.html: \
		$(SRC)/%.md \
		$(PANDOC_DIR)/page.html \
		$(wildcard $(SRC)/*.bib)
	@echo "Generating document \"$@\"..." 1>&2
	@-mkdir -p "$(@D)"
	@-mkdir -p "$(patsubst $(DEST)/%,$(CACHE)/%,$(@D))"
	@pandoc  \
		--metadata path='$(shell realpath $(@D) --relative-to $(DEST) --canonicalize-missing)' \
		--metadata root='$(shell realpath $(DEST) --relative-to $(@D) --canonicalize-missing)' \
		--metadata index='$(shell realpath $(DEST)/index.html --relative-to $(@D) --canonicalize-missing)' \
		--metadata default-style='$(STYLE)' \
		--metadata last-modified='$(shell date -r "$<" '+%Y-%m-%d')' \
		$(if $(wildcard $(SRC)/favicon.*),--metadata favicon='$(shell realpath $(DEST)/favicon.ico --relative-to $(@D) --canonicalize-missing)') \
		--from markdown+smart+fenced_divs+inline_notes+table_captions \
		--to html5 \
		--standalone \
		--template '$(PANDOC_DIR)/page.html' \
		--filter pandoc-citeproc \
		$(foreach F,\
			$(filter %.bib, $^),\
			--bibliography='$(F)' \
		)\
		--shift-heading-level-by=1 \
		--ascii \
		--strip-comments \
		--email-obfuscation=references \
		--highlight-style=kate \
		$< \
		$(filter %/metadata.yaml, $^) \
		| sed ':a;N;$$!ba;s|>\s*<|><|g' \
		> $@

# Create PDF documents
$(DEST)/%.pdf: $(SRC)/%.md $(PANDOC_DIR)/page.html # additional deps generated by dynamic.mk in snel-index.mk
	@echo "Generating document \"$@\"..." 1>&2
	@-mkdir -p "$(@D)"
	@pandoc \
	    --shift-heading-level-by=1 \
	    --pdf-engine=weasyprint \
        --pdf-engine-opt=-u"$(@D)" \
	    --template '$(PANDOC_DIR)/page.html' \
	    --metadata default-style='$(STYLE)' \
        --metadata root='$(shell realpath $(DEST) --relative-to $(@D) --canonicalize-missing)' \
	    --to pdf \
	    $< \
	| ps2pdf \
		-dOptimize=true \
		-dUseFlateCompression=true \
		-dEmbedAllFonts=true \
		-dPrinted=false \
		- $@

